// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV6TiAOypowEIwKiBPd46nYNIHZU2Lw14',
    appId: '1:555718417628:web:de754578937e1dab4be819',
    messagingSenderId: '555718417628',
    projectId: 'portfolio-782e9',
    authDomain: 'portfolio-782e9.firebaseapp.com',
    storageBucket: 'portfolio-782e9.firebasestorage.app',
    measurementId: 'G-DMWX170PZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJemnZV4Seo9n_atjl-FIrGEKa1yf95Ww',
    appId: '1:555718417628:android:efd938149254de844be819',
    messagingSenderId: '555718417628',
    projectId: 'portfolio-782e9',
    storageBucket: 'portfolio-782e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwUlLQUxAmcu6-k3onacgaUX_8DrZqwkw',
    appId: '1:555718417628:ios:b6c3e43ba75d4f8e4be819',
    messagingSenderId: '555718417628',
    projectId: 'portfolio-782e9',
    storageBucket: 'portfolio-782e9.firebasestorage.app',
    iosClientId: '555718417628-v5r90hccobuaf7jhs6p5ahbpbh28cnk3.apps.googleusercontent.com',
    iosBundleId: 'com.codingliquids.paulinaKnop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBteJ2zmqFASOcxok7T-hlAkx6CpT2yoc',
    appId: '1:555718417628:web:678ba3c81f59be354be819',
    messagingSenderId: '555718417628',
    projectId: 'portfolio-782e9',
    authDomain: 'portfolio-782e9.firebaseapp.com',
    storageBucket: 'portfolio-782e9.firebasestorage.app',
    measurementId: 'G-JF0GKJ5MRS',
  );

}