name: iOS CI - Xcode 15

on:
  push:
    branches: [ "**" ]

jobs:
  build_ios_xcode15:
    name: Build iOS (Xcode 15 + Swift flag)
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode 15.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.32.5'

      - name: Get Packages
        run: flutter pub get

      - name: Prepare iOS project (iOS 13 target + Swift flag)
        run: |
          # Generate Podfile if it doesn't exist
          if [ ! -f ios/Podfile ]; then
            flutter build ios --no-codesign --simulator || true
          fi

          # Ensure platform iOS 13 in Podfile
          if grep -qE "^platform :ios" ios/Podfile; then
            sed -i '' -E "s/^platform :ios, *'[0-9.]+'/platform :ios, '13.0'/" ios/Podfile
          else
            sed -i '' "1s/^/platform :ios, '13.0'\n/" ios/Podfile
          fi

          # Inject Swift preview flag to Firebase pods
          if ! grep -q "AccessLevelOnImport" ios/Podfile; then
            cat >> ios/Podfile <<'EOF'
          post_install do |installer|
          installer.pods_project.targets.each do |t|
          if ['FirebaseCoreInternal', 'FirebaseSessions'].include? t.name
          t.build_configurations.each do |c|
          flags = c.build_settings['OTHER_SWIFT_FLAGS'] || '$(inherited)'
          c.build_settings['OTHER_SWIFT_FLAGS'] = "#{flags} -enable-experimental-feature AccessLevelOnImport"
          end
          end
          end
          end
          EOF
          fi
  
          # Bump deployment target in Xcode project to 13.0
          sed -i '' -E 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]+\.[0-9]+/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' ios/Runner.xcodeproj/project.pbxproj

          - name: Install CocoaPods dependencies
            run: |
              cd ios
              pod install --repo-update
              cd ..

      - name: Build iOS (no codesign)
        run: flutter build ios --no-codesign
